### ISSUE TITLE
Website docs don't show any examples anymore

### ISSUE THREAD

**Issue by safejace** [Stegosource/vuetensils#141]
not sure what happened. but i've loaded the site on multiple browsers with and without extensions and the examples aren't rendered on the page

Checked out the site on the way back machine and the examples are there

**Comment by AustinGil** [comment]
Yeah, I'm in the middle of a migration to Vuepress next. Unfortunately, vuepress-plugin-live does not currently support it, so I'm deciding if I make a PR to that project, fork it, or use Codesandbox. For maintenance reasons, I want to keep this upgrade. Please be patient as I work out a solution, but I fully intend to have live examples in the docs. I just want to make sure that they work when deployed as well as within readme files.

**Comment by AustinGil** [comment]
Just wanted to post a quick update here. I got on a live stream with the creator of vuepress-plugin-live and the good news is that we figured out how to support vuepress@next and the vuetensils docs. The bad news is it breaks during build time. So seems like just a bit more to figure out what that issue is, then I can make a PR to that project, and pull it in over here.

**Comment by aaronransley** [comment]
Excited to see those working demos! Absolutely love using `vuetensils`, thanks for all the hard work @AustinGil!

Do you happen to have a link to the VOD / livestream archive for that `vuepress-plugin-live` stream? Would be fun to put that on the ol' second monitor.

**Comment by AustinGil** [comment]
Thanks so much @aaronransley. It's been a lot of work, but I use it a lot and enjoy dogfooding it. I just wish I had more time (and more skills).

Here's the video: https://www.youtube.com/watch?v=_yh7KH92zL4

**Comment by AustinGil** [comment]
Finally got this working again thanks to the wonderful @elevatebart.

I still need to adjust the layouts, but the examples are working again :D
