### ISSUE TITLE
Vuetensils: TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by bmcalees** [Stegosource/vuetensils#143]
Upgrading from 9.3 -> 10.7 is giving the following error across all pages of the project. Any idea what could cause this?

![image](https://user-images.githubusercontent.com/7414766/170566749-466194d9-2bc0-4500-882c-521bb0a3fbf2.png)

**Comment by AustinGil** [comment]
Not the most obvious error, but looking at the source, like 113 of the dist file references a function that is related to VAlert. Can you share how you're using it?

Or better yet, can you create a reproduction of the issue in CodeSandbox?

**Comment by bmcalees** [comment]
> Not the most obvious error, but looking at the source, like 113 of the dist file references a function that is related to VAlert. Can you share how you're using it?
> 
> Or better yet, can you create a reproduction of the issue in CodeSandbox?

I noticed that as well and we're actually not using VAlert anywhere in the codebase which is why I was also confused. This is the RevealBio codebase btw. I'll try to throw together a codepen to reproduce the issue!

**Comment by AustinGil** [comment]
You might also try the latest version, 0.11.0.

**Comment by bmcalees** [comment]
0.11.0 was broken too.

It looks like we're doing some form of global component registration which I don't see referenced anywhere in the docs.

![image](https://user-images.githubusercontent.com/7414766/170589242-0e84c733-646e-483f-a761-4a513297e67d.png)

Importing Vuetensils is what causes everything to break. 

Importing the components as shown in the docs seems to make everything work fine again!

![image](https://user-images.githubusercontent.com/7414766/170589989-bebd149e-1b13-48f5-a086-eeb92a06cd86.png)

I'm going to close this issue.

**Comment by AustinGil** [comment]
Huh, that's weird. It should actually now support multiple ways of registering global components including your example. I made a demo that shows it working

https://codesandbox.io/s/pensive-andras-hs4bzx?file=/src/main.js

Anyway, I'm glad you have it sorted.
