### ISSUE TITLE
Enable class customisation for individual notifications

### ISSUE THREAD

**Issue by davidsandoz** [Stegosource/vuetensils#154]
Currently, the `VNotifications` component can take a `classes` prop to have custom classes assigned to all the notifications.

When notifying a user of an error or a warning, we may want the notification to have a different appearance. To do this, it would be useful to be able to provide a custom class when calling the `notify` function so that the class is applied only to that specific notification.

Could this be implemented? Or would there be an existing alternative way to reach the desired result?

**Comment by AustinGil** [comment]
Hi @davidsandoz. Thank you for the contribution. I think this is a great idea, and one that would be pretty easy to implement. I'm out of town today, but I think it's worth adding. Good thinking :)

**Comment by AustinGil** [comment]
@davidsandoz  can you try out v 0.13.3 and see how it feels? Also updated the docs to reflect the changes https://vuetensils.com/components/Notifications.html

**Comment by davidsandoz** [comment]
@AustinGil It works very well, thanks!

**Comment by AustinGil** [comment]
Sick!
