### ISSUE TITLE
[Bug] Overflow:hidden in VToggle

### ISSUE THREAD

**Issue by jllagerberg** [Stegosource/vuetensils#37]
The `overflow: hidden;` part in the `VToggle.vue` causes problem if you have elements that goes out of the toggle box. For example if you have a long dropdown.

**Comment by jllagerberg** [comment]
Made a pull request which fixes it.

**Comment by Stegosource** [comment]
Thanks! I actually read through that article when I created this component but did not follow it closely enough it would seem.
Good catch on that one.

**Comment by jllagerberg** [comment]
You can actually ignore my pull request, since I managed to get it working with your code. 

Make sure that the resets are not `null`, but an empty string instead. That way it also works in IE11.

```
methods: {
    collapse(element) {
      element.style.height = 0;
    },
    expand(element) {
      element.style.transition = 'height .3s ease';
      element.style.overflow = 'hidden';
      element.style.height = `${element.scrollHeight}px`;
      // Force repaint to make sure the animation is triggered correctly.
      element.scrollHeight;
    },
    resetHeight(element) {
      element.style.overflow = 'visible';
      element.style.height = '';
    },
  },
```

**Comment by Stegosource** [comment]
@jllagerberg Thanks. I wanted to let you know that I'm not ignoring your PR's but I'm getting married this Sunday, so the last two weeks all my free time has been dedicated to that. Next week things should come back to normal, and I have 2 updated pretty much ready to be pushed out, including yours. I'll make the changes above and update them then.

Again, sorry for the delay, but hang tight and I'll have it up next week for sure.

**Comment by jllagerberg** [comment]
That's awesome, congrats man! Life comes before coding.
And there's no hurry from my part, so don't worry about that :)

**Comment by Stegosource** [comment]
Hey, @jllagerberg I just published the changes. Can you give it a try and let me know?

**Comment by jllagerberg** [comment]
The `overflow: hidden` is still in the CSS, but I can see that you changed it in the .vue-file. Did you forget to update something?

![Untitled2](https://user-images.githubusercontent.com/27690759/67157493-17ce8880-f32d-11e9-9e05-b3dab0bb5a16.jpg)

**Comment by Stegosource** [comment]
@jllagerberg I realized I made the changes but did not publish the built files. Should be working now. Hehe.

**Comment by jllagerberg** [comment]
Looking good!
