### ISSUE TITLE
[Feature Request] IE11 support

### ISSUE THREAD

**Issue by jllagerberg** [Stegosource/vuetensils#39]
This project has no support for IE11. It's not really accessible if that is not supported.

**Comment by Stegosource** [comment]
You are correct. Accessibility relates to browser support as well. However, this issue brings up a lot of different points:
- IE11 is no longer officially maintained by Microsoft
- Components are imported on an individual basis and most work just fine in IE11
- World usage for IE11 is about 2%.

All this to say that I won't ignore IE11 support. I think it's important to provide as much browser support as makes sense. But this is still a relatively new project and right now I'm the only maintainer. There are some other improvements I'm focusing one that I think provide more value to both developers and the end-users.

**Comment by jllagerberg** [comment]
Well, that's not entirely true. According to Microsoft, IE11 is supported until the end of Windows 10 which is the year 2025. It's the support for IE10 that will end soon.

But I hear you, I hate IE as much as anyone else. But IE11 support is unfortunately mandatory for a lot of projects these days.

If you could fix the initial problems, with the project not even opening in IE11, I will be able to help you maintain this. I was planning to use this on a relatively big project and I could look for bugs and improvements as I code along using the package.

**Comment by Stegosource** [comment]
Ahhh. That explains all the bug reports ;)

I'm glad to hear you will be using this on a project soon. Keep in mind that it's not at the V1 release yet.

Also glad to hear you are interested in working on it. Since it's mostly been just scratching my own itch, it's hard to know how it can better serve others. It will be good to get some outside perspective and real-life use cases. 

And yes, you are right. I had confused that EOL with IE10. I'll take a look at getting it working on IE11.

**Comment by jllagerberg** [comment]
> Keep in mind that it's not at the V1 release yet.

I know. But everything is an improvement for us at this point :)

**Comment by Stegosource** [comment]
> I know. But everything is an improvement for us at this point :)
Great. Well I was also going to write some in depth articles about each specific component and the why/how to of making them accessible. Is that something you would be interested in?

Actually, what is your main interest in using this project? The accessibility features, the base functionality, the naked components, or something else?

**Comment by jllagerberg** [comment]
We started a new project last month, where my colleagues wanted to go with Vuetify. But I do most of the frontend, so I can't be arsed having to override everything basically. It would just end with us using it for accessibility reasons, which doesn't feel that optimised really.

But I am still a novice when it comes to aria and such, which is also a reason why I need a tool like this. So I wouldn't be much help in writing articles at the moment I'm afraid.

**Comment by Stegosource** [comment]
That sounds like the perfect fit. 

Also, I wasn't asking for your help in writing articles. I was asking if that is something you would be interested in reading about. Something else you might consider for your project is just copying the source code for the components you need and hacking it to your purposes. Then you won't have to worry about any breaking changes.

**Comment by jllagerberg** [comment]
> Also, I wasn't asking for your help in writing articles. I was asking if that is something you would be interested in reading about. 

Yes, absolutely! That would actually be really great.

> Something else you might consider for your project is just copying the source code for the components you need and hacking it to your purposes. Then you won't have to worry about any breaking changes.

I know, but I wouldn't mind helping either. I think a library like this could benefit a lot of people.

**Comment by focussing** [comment]
👍 
The 2% number is correct, but within schools the IE11 percentage is 28%... (yep).
It would be great to have IE11 compatibility; for now a list of what is, and what is not working would be great!
Currently I use bootstrap, but I tend to dislike the bloated result more and more.

Also I could help in testing new releases :)

**Comment by Stegosource** [comment]
Circling back on this, as one IE11 issue has been addressed. @jllagerberg or @focussing could one of you put together a more detailed list of what does not work in IE11? I use Ubuntu, so I can't really test it out. I can probably find a machine that has it if it's not convenient for you.

**Comment by jllagerberg** [comment]
Absolutely.

A more convenient way for you to test things as well would be lambdatest.com. They have a free tier for testing in IE11.

**Comment by Stegosource** [comment]
Yeah, looked into this. Nothing works!!!!
Lol. The good news is it seems like it's just an issue with ES6. I imaging some thing will be available if I can transpile the code with Babel. Some things will not be available such as the Async component due to Promises not being a feature in IE11, but Babel should provide some good support. I just need to figure out how to set it up with Rollup.

**Comment by jllagerberg** [comment]
Actually, I think most of it works in IE11. It's just not working in Vuepress.
The VToggle works for me in IE11, for example.

**Comment by Stegosource** [comment]
Yeah, I thought that would be the case. Most of the components in this library are intended to be imported into projects that THEN handle the transpilation step. I was looking into that issue on Vuepress but did not figure it out. Glad to hear it's working. There's some other cool features coming soon. I'm adding some useful directives.

**Comment by focussing** [comment]
Great! Looking forward to that.
I'm on "watch releases" to I'll be notified :)

I am creating a Vue test project with all your components used.
So I can easily update, test in development and make distribution to be tested on IE11.

By the way, does something exists to test development on IE11 when working on a mac?
(I do not mean via a virtual machine)

**Comment by jllagerberg** [comment]
> By the way, does something exist to test development on IE11 when working on a mac?
> (I do not mean via a virtual machine)

I've never used a Mac for development, but I know there are ways to install Windows on a Mac. That's the only way to test IE11 on your own device, since you can't get IE11 on the Mac iOS.

**Comment by focussing** [comment]
Yep, I use VMware for that. But it might be very easy if there was some kind of IE11-thingy for Mac...

**Comment by focussing** [comment]
@Stegosource do you have a "dialog" component on your list? :)

**Comment by Stegosource** [comment]
@focussing you can use https://www.lambdatest.com/ to launch a remote virtual machine for a browser session. It supports IE11 on Windows 8.1 with the free version. 

And regarding the "dialogue", I have the 'VModal' component which is pretty much the same thing. I might switch it to use the name VDialogue, and it doesn't currently use the <dialogue> tag, but as more support comes, I'll add that as well.
