### ISSUE TITLE
v-copy directive does not seems to work on nuxt/vuetify

### ISSUE THREAD

**Issue by andrewspy** [Stegosource/vuetensils#42]
Does anybody manage to get it to work on nuxt/vuetify? Below is a sample code, which does not work in my case.

```html
<v-btn v-copy="`Text copied`" outlined>
    <v-icon left>mdi-content-copy</v-icon>
    Copy
</v-btn>
```

**Comment by Stegosource** [comment]
This is interesting. I'm taking a look into it now. In the meantime, you can try https://github.com/egoist/v-copy and see if that works. I'll update when I know more.

**Comment by mahmoudyusof** [comment]
I don't know if this bug was fixed, but it works fine with me now, are you sure you added the directive.
```
import { copy } from "vuetensils";
Vue.directive("copy", copy);
```

**Comment by andrewspy** [comment]
@mahmoudyusof I did add the directive as per what you suggest, and it doesn't seem to work on nuxt/vuetify2.

**Comment by Stegosource** [comment]
@mahmoudyusof thanks for chiming in on this. I'm glad it's working as intended for you. However, I confirmed the issue that @andrewspy described. Still not sure what is causing it, but there is a conflict on how things work with Vuetify. I hope to find a solution, but have not isolated the problem yet. Sorry @andrewspy  :/

**Comment by Stegosource** [comment]
Good news @andrewspy. I had some time to look into this tonight and may have found the issue. I got the code working with Vuetify and a local version of Vuetensils. Just pushed up the latest release v0.4.4 with the fix. If you could give that a shot and let me know, that would be swell.

**Comment by andrewspy** [comment]
@Stegosource I have updated to latest release v0.4.4 and everything is working as expected now! Thanks!

**Comment by Stegosource** [comment]
Woot!
Sorry for the delay.
