### ISSUE TITLE
VInput checkbox default value isn't applied.

### ISSUE THREAD

**Issue by mgambill** [Stegosource/vuetensils#50]
The initial value isn't setting properly on checkbox.
`<VInput label="Checkbox Item" type="checkbox" v-model="checkboxValue"  />`

`data(){
  return { checkboxValue: true }
}`

should be able to add the following to the component to fix:
`:checked="$attrs.type === 'checkbox' && value === true"`

**Comment by Stegosource** [comment]
This will be fixed in the next release.

**Comment by Stegosource** [comment]
Just published 0.4.5 with this fixed
