### ISSUE TITLE
Error after upgrading from 0.4.4 to 0.5.0

### ISSUE THREAD

**Issue by callumflack** [Stegosource/vuetensils#59]
Love this lib!

I upgraded from 0.4.4 to 0.5.0 in a Nuxt project and got this error:

![image](https://user-images.githubusercontent.com/749885/74079524-6478d380-4a84-11ea-96fe-46224cb2a9ec.png)

(Rolling my version back for now)

**Comment by brandonpittman** [comment]
Try installing the missing dependency.

**Comment by callumflack** [comment]
Thanks @brandonpittman, worked. I lazily presumed it being a missing Vuetensils requirement. 

Should it be noted in the docs?

**Comment by Stegosource** [comment]
@brandonpittman thanks for jumping on this so quick!

@callumflack this is an interesting issue because Vuetensils doesnt actually have any dependencies in the package.json file. But clearly from the error message, there was something missing. I'm also curious why it only came up after upgrading to 0.5.

Can you share some more information about how your project is set up? Did you use the Vue CLI? Is there a repo anywhere I can take a look at?

Also, I'm glad you like the library. It feels like it still has a long way to go, but it's coming along :)

**Comment by callumflack** [comment]
@Stegosource it’s certainly coming along. Things like this are what Bootstrap (yuck) hoped to be but forgot to remember…

This issue occurs on Nuxt 2.8.1+ projects (tried exact upgrades from 0.4.4 to 0.5 on 2 separate Nuxt projects).

Also strange that after installing `vue-runtime-helpers`it doesn’t get added to the package.json

**Comment by callumflack** [comment]
Repos are private, happy to add you for a look-see if you wish?

**Comment by Stegosource** [comment]
I got no hate for Bootstrap. I think they continue to do a good job, but there's different tools for different projects.

Maybe I should add that as a dependency. I'll have to play around with Nuxt. I've also got it running on a Gridsome project, but I haven't tested the upgrade yet, so I'll give that a go.

If you're saying it occurs on just a standard Nuxt install, then there is no need to add me to the project. I'll take a look and see if it's something I can reproduce.

**Comment by callumflack** [comment]
Not to go on too much, but Bootstrap greatly contributed to the homogeneity of website visual design between 2013–2018. If brand is important (when is it not?) then care should be taken to strip any  interaction library of styling themes — focus on doing one job well. You do that here, and that is why I think it's a terrific lib.

**Comment by brandonpittman** [comment]
Gridsome has the same issue. Installed the package manually and it fixed it.

**Comment by callumflack** [comment]
My mate @barryph runs a linux a machine and handles Node versions with NVM — he had no issue with requiring this dependency

**Comment by Stegosource** [comment]
Oh yeah, that makes more sense. I run Linux as well and use NVM for Node. What is your OS?

**Comment by Stegosource** [comment]
This may be an issue with Rollup. Just going off this thread https://stackoverflow.com/questions/54379726/rollup-plugin-vue-v4-6-2-has-a-problem-with-vue-runtime-helpers

**Comment by Stegosource** [comment]
Just published a new release that I THINK will fix this.

**Comment by callumflack** [comment]
@Stegosource I'm on a Mac. Removing `vue-runtime-helpers` then upgrading `vuetensils` worked : )

Thank you! Look forward to contributing to conversations the future of this lib, when I get past these deadlines —
