### ISSUE TITLE
[Feature request] add a changelog file

### ISSUE THREAD

**Issue by focussing** [Stegosource/vuetensils#63]
Hi @Stegosource,

Let's say once a week I check overhere if something nice has happened.
Would it be an idea to create a (small) changelog file so one can see if new components have been changed or added?

**Comment by Stegosource** [comment]
Oh yeah, I'm currently not pushing out changes THAT often. Got another project Im trying to finish up at the moment before I come back to this one. But YES a changelog has been on my todo list. Id like to have some sort of automated one, but Im not sure how best to do that.

**Comment by Stegosource** [comment]
Closing this issue as I've JUST added one to my local dev branch

**Comment by focussing** [comment]
Great!! Thank you @Stegosource

**Comment by hacknug** [comment]
Still no public changelog?

**Comment by AustinGil** [comment]
Yeah. I tried setting up an automated system based on commits, but it didn't end up working very well, unfortunately. As it stands now, I don't have plans to create a public changelog.
