### ISSUE TITLE
[Bug] vts-input--invalid not working in any case

### ISSUE THREAD

**Issue by nles** [Stegosource/vuetensils#66]
Noticed that `vts-input--invalid` does not work at all. Seems to be due to a reference to `invalid.anyInvalid`, which does not exist. Referencing just `anyInvalid` seems to work. There's few other places in the file with the same reference to this non-existent variable.

Would also make sense to have the `vts-input--invalid` class to only be added when input is dirty, similar to how it is in your docs (like `state.dirty && state.anyInvalid`).

**Comment by nles** [comment]
Created a pull request: https://github.com/Stegosource/vuetensils/pull/67

**Comment by Stegosource** [comment]
Thanks @nles. PR merged. Nice work!
