### ISSUE TITLE
Dependencies are out of date - 4 breaking, 107 versions behind

### ISSUE THREAD

**Issue by TheJaredWilcurt** [Stegosource/vuetensils#76]
# There have been **[4](# '4')** breaking changes.

### 1 package skipped, per ManifestComments.

Status | Package | Version | Type | Latest | Behind by | Breaking
:-- | :-- | :-- | :-- | :-- | :-- | :--
&#9888; | [@babel/core](https://www.npmjs.com/package/@babel/core) | 7.8.7 | devDependencies | 7.9.6 | 2 | 0
&#9888; | [@babel/preset-env](https://www.npmjs.com/package/@babel/preset-env) | 7.9.5 | devDependencies | 7.9.6 | 1 | 0
&#10004; | [@commitlint/cli](https://www.npmjs.com/package/@commitlint/cli) | 8.3.5 | devDependencies | 8.3.5 | 0 | 0
&#10004; | [@commitlint/config-conventional](https://www.npmjs.com/package/@commitlint/config-conventional) | 8.3.4 | devDependencies | 8.3.4 | 0 | 0
&#10004; | [@commitlint/prompt](https://www.npmjs.com/package/@commitlint/prompt) | 8.3.5 | devDependencies | 8.3.5 | 0 | 0
&#9888; | [@rollup/plugin-commonjs](https://www.npmjs.com/package/@rollup/plugin-commonjs) | 11.0.2 | devDependencies | 11.1.0 | 1 | 0
&#10004; | [@vue/test-utils](https://www.npmjs.com/package/@vue/test-utils) | 1.0.2 | devDependencies | 1.0.2 | 0 | 0
&#9888; | [@vuepress/plugin-google-analytics](https://www.npmjs.com/package/@vuepress/plugin-google-analytics) | 1.4.0 | devDependencies | 1.5.0 | 2 | 0
&#10004; | [babel-core](https://www.npmjs.com/package/babel-core) | 7.0.0-bridge.0 | devDependencies | 6.26.3 | 0 | 0
&#10004; | [babel-eslint](https://www.npmjs.com/package/babel-eslint) | 10.1.0 | devDependencies | 10.1.0 | 0 | 0
&#10004; | [babel-jest](https://www.npmjs.com/package/babel-jest) | 26.0.1 | devDependencies | 26.0.1 | 0 | 0
&#9888; | [babel-loader](https://www.npmjs.com/package/babel-loader) | 8.0.6 | devDependencies | 8.1.0 | 1 | 0
&#9888; | [commitizen](https://www.npmjs.com/package/commitizen) | 4.0.3 | devDependencies | 4.1.2 | 5 | 0
&#9888; | [cz-conventional-changelog](https://www.npmjs.com/package/cz-conventional-changelog) | 3.1.0 | devDependencies | 3.2.0 | 2 | 0
&#128165; | [eslint](https://www.npmjs.com/package/eslint) | 6.8.0 | devDependencies | 7.0.0 | 6 | 1
&#10004; | [eslint-plugin-vue](https://www.npmjs.com/package/eslint-plugin-vue) | 6.2.2 | devDependencies | 6.2.2 | 0 | 0
&#9888; | [husky](https://www.npmjs.com/package/husky) | 4.2.3 | devDependencies | 4.2.5 | 2 | 0
&#10004; | [jest-serializer-vue-tjw](https://www.npmjs.com/package/jest-serializer-vue-tjw) | 3.14.0 | devDependencies | 3.14.0 | 0 | 0
&#10004; | [minimist](https://www.npmjs.com/package/minimist) | 1.2.5 | devDependencies | 1.2.5 | 0 | 0
&#9888; | [release-it](https://www.npmjs.com/package/release-it) | 13.1.1 | devDependencies | 13.5.8 | 20 | 0
&#9888; | [rollup](https://www.npmjs.com/package/rollup) | 2.1.0 | devDependencies | 2.10.0 | 24 | 0
&#10004; | [rollup-plugin-buble](https://www.npmjs.com/package/rollup-plugin-buble) | 0.19.8 | devDependencies | 0.19.8 | 0 | 0
&#128165; | [rollup-plugin-filesize](https://www.npmjs.com/package/rollup-plugin-filesize) | 6.2.1 | devDependencies | 9.0.0 | 7 | 3
&#10004; | [rollup-plugin-replace](https://www.npmjs.com/package/rollup-plugin-replace) | 2.2.0 | devDependencies | 2.2.0 | 0 | 0
&#10004; | [rollup-plugin-uglify-es](https://www.npmjs.com/package/rollup-plugin-uglify-es) | 0.0.1 | devDependencies | 0.0.1 | 0 | 0
&#9888; | [rollup-plugin-vue](https://www.npmjs.com/package/rollup-plugin-vue) | 5.1.6 | devDependencies | 5.1.7 | 12 | 0
&#9888; | [stylelint](https://www.npmjs.com/package/stylelint) | 13.2.1 | devDependencies | 13.3.3 | 4 | 0
&#10004; | [stylelint-config-sass-guidelines](https://www.npmjs.com/package/stylelint-config-sass-guidelines) | 7.0.0 | devDependencies | 7.0.0 | 0 | 0
&#9888; | [vue-docgen-api](https://www.npmjs.com/package/vue-docgen-api) | 4.14.0 | devDependencies | 4.22.3 | 12 | 0
&#10004; | [vue-jest](https://www.npmjs.com/package/vue-jest) | 3.0.5 | devDependencies | 3.0.5 | 0 | 0
&#10004; | [vue-router](https://www.npmjs.com/package/vue-router) | 3.1.6 | devDependencies | 3.1.6 | 0 | 0
&#9888; | [vuepress](https://www.npmjs.com/package/vuepress) | 1.4.0 | devDependencies | 1.5.0 | 2 | 0
&#10004; | [vuepress-plugin-docgen](https://www.npmjs.com/package/vuepress-plugin-docgen) | 1.2.9 | devDependencies | 1.2.9 | 0 | 0
&#9888; | [vuepress-plugin-live](https://www.npmjs.com/package/vuepress-plugin-live) | 1.4.2 | devDependencies | 1.5.3 | 4 | 0

Auto-Generated with [DepChecker](https://github.com/TheJaredWilcurt/depchecker).

**Comment by TheJaredWilcurt** [comment]
Did this from my Jest testing branch, since it adds several new dependencies.

**Comment by TheJaredWilcurt** [comment]
Will be fixed by #77

**Comment by Stegosource** [comment]
Fixed
