### ISSUE TITLE
A11y automated testing

### ISSUE THREAD

**Issue by TheJaredWilcurt** [Stegosource/vuetensils#79]
* [x] [ESlint-Plugin-Vue-A11y](https://www.npmjs.com/package/eslint-plugin-vue-a11y) - This is a pretty easy win. Just a lint plugin to catch some simple stuff.
* [x] [Pa11y](https://pa11y.org) - is a pretty good tool. It could test against the built docs pages for WCAG/Section 508. Would take a little more time to set up, but could then automate reports.

**Comment by Stegosource** [comment]
Yeah, this is a good idea. I've got some local a11y linters set up which catch stuff locally, but if more folks start contributing then integrated a11y linting on commit would be a good step, and then in CI/CD is even better.

Great idea!

**Comment by TheJaredWilcurt** [comment]
I'm pretty strongly against tying anything into git hooks. It just breaks too many git GUI's, and it forces people with different workflows into something that may be inconvenient. Just having a CI run the check is fine. As long as you can't merge to master until those are fixed, it doesn't matter if it's done on every commit, or as the last commit.
