### ISSUE TITLE
VInput:  Programatically updated value of v-model isn't reflected in the input element

### ISSUE THREAD

**Issue by neilh-cogapp** [Stegosource/vuetensils#92]
Hello - thanks for the cool library. Just wondered if this is a possible bug?

```
<VInput v-model="query" />
<button @click="handleClick">Clear input<button>

...

data() {
  query: "",
},
methods: {
  handleClick() {
    this.query = "";
  },
}
```

1. Enter a value into the input
2. Clicking the button (or setting value of `this.query` programatically) results in the value of `this.query` being correctly set, but the value shown to the user in the input is not updated.

**Comment by Stegosource** [comment]
Just tested this out. The issue makes sense why it's happening, but it's not the expected behavior. I should be able to fix it though :)

Thanks for reporting

**Comment by neilh-cogapp** [comment]
Thanks for the quick response, happy to help.

**Comment by Stegosource** [comment]
I believe this issue is fixed and will be out in the next minor release.

**Comment by neilh-cogapp** [comment]
0.7.2 has fixed the issue. Thank you very much.
